In [16]:
import numpy as np
a =np.random.randint(2,100,(5,5))
print(a)

[[49 28 92 42 37]
 [24 54 21 32 15]
 [61 93  9 95 55]
 [64  9 67 78 58]
 [30 14 45 18 28]]


In [17]:
#(a) middle element of the array
middle_element=a[2,2]
print(middle_element)

9


In [18]:
#(b) mean of each row of the array
row_mean=np.mean(a,axis=1)
print(row_mean)

[49.6 29.2 62.6 55.2 27. ]


In [19]:
#(c) original array that are greater than the overall mean of the array
new_array=a[a>np.mean(a)]
print(new_array)

[49 92 54 61 93 95 55 64 67 78 58 45]


In [36]:
import numpy as np

def numpy_spiral_order(matrix):
    if matrix.size == 0:
        return []
    if matrix.shape[0] == 1:
        return matrix[0].tolist()
    if matrix.shape[1] == 1:
        return matrix[:, 0].tolist()

    spiral = []
    spiral.extend(matrix[0, :].tolist())
    spiral.extend(matrix[1:-1, -1].tolist())
    spiral.extend(matrix[-1, ::-1].tolist())
    spiral.extend(matrix[-2:0:-1, 0].tolist())
    spiral.extend(numpy_spiral_order(matrix[1:-1, 1:-1]))

    return spiral


In [37]:
# Testing the spiral function
t=np.arange(1,26,1)
t=np.reshape(t,(5,5))
print(t)
print(numpy_spiral_order(t))



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1, 2, 3, 4, 5, 10, 15, 20, 25, 24, 23, 22, 21, 16, 11, 6, 7, 8, 9, 14, 19, 18, 17, 12, 13]
